excel_report:
  target: "{{ env_var('DBT_TARGET') }}"
  outputs:
    local_dev:
      type: sqlserver
      driver: 'ODBC Driver 17 for SQL Server'
      server: "{{ env_var('SQL_SERVER') }}"
      database: "{{ env_var('SQL_SERVER_DATABASE') }}" 
      schema: "{{ env_var('SQL_SERVER_SCHEMA') }}"  
      port: 1433
      windows_login: True
      trust_cert: True
    dev:
      type: postgres
      host: "{{ env_var('postgres_HOST') }}"
      user: "{{ env_var('postgres_USER') }}"
      password: "{{ env_var('postgres_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('postgres_DBNAME') }}"
      schema: "{{ env_var('postgres_SCHEMA') }}"
      threads: 1
      connect_timeout: 10