excel_report:
  target: "{{ env_var('DBT_TARGET') }}"
  outputs:
    local_dev:
      type: sqlserver
      driver: 'ODBC Driver 17 for SQL Server'
      server: "{{ env_var('SQL_SERVER') }}"
      database: "{{ env_var('SQL_SERVER_DATABASE') }}" 
      schema: "{{ env_var('SQL_SERVER_SCHEMA') }}"  
      port: 1433
      windows_login: True
      trust_cert: True
    dev:
      type: snowflake
      database: "{{ env_var('DBT_DB_NAME') }}"
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_ENV_SECRET_PASSWORD') }}"
      schema: "{{ env_var('AIRFLOW_ENVIRONMENT') }}"
      warehouse: "{{ env_var('DBT_WAREHOUSE') }}"
      account:  "{{ env_var('DBT_ACCOUNT') }}"
      role:  "{{ env_var('DBT_ROLE') }}"
      client_session_keep_alive: True
      threads: 1